version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=timessheet_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - mysqldb
    image: mou
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/timessheet_db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "hibernate.dialect": "org.hibernate.dialect.MySQL57Dialect",
        "hibernate.hbm2ddl.auto": "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db :